apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmaps-service-deployment
  labels:
    app: gmaps-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmaps-service
  template:
    metadata:
      labels:
        app: gmaps-service
    spec:
      containers:
      - name: gmaps-service
        image: 092356264921.dkr.ecr.eu-central-1.amazonaws.com/gmaps-service:d651327269de64c26c013b6487dfa2aaf88b418f
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5