apiVersion: v1
kind: Service
metadata:
  name: gmaps-service-service
spec:
  selector:
    app: gmaps-service
  ports:
    - name: rest
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 90
      targetPort: 9000
  type: ClusterIP